### ISSUE TITLE
Why this regex is considered unsafe?

### ISSUE THREAD

**Issue by zhaozhiming** [substack/safe-regex#10]
I have a regex to match the localhost IPv4 ip, but `safe-regex` think it unsafe.
When I remove the `{3}` the result is true and I repeat the `(\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))` 3 times the result is true too.
But I don't know why. Please help. Thanks.

```sh
$ node safe.js '^127(\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$'
false
$ node safe.js '^127(\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))$'
true
$ node safe.js '^127(\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))$'
true
```

**Comment by davisjam** [comment]
safe-regex checks for nested quantifiers. It does not like your idiom of (X?){3}, which has an inner quantifier of ? and an outer quantifier of {3}. However, in practice I do not believe that your idiom is vulnerable to ReDoS attack.

**Comment by davisjam** [comment]
Here is a simple representative example:

```
(16:10:41) jamie@woody /tmp/safe-regex $ cat simple.js 
var safe = require('./index.js');
console.log(safe('(X?){3}'))

(16:10:42) jamie@woody /tmp/safe-regex $ node simple.js 
false
```

**Comment by zhaozhiming** [comment]
Thank you @davisjam
