### ISSUE TITLE
Installation instructions install a different fork of this library

### ISSUE THREAD

**Issue by tcoughlin3** [substack/safe-regex#22]
```
npm install safe-regex
```

[This fork](https://github.com/davisjam/safe-regex) is registered with npm as `safe-regex` so I'm not getting https://github.com/substack/safe-regex with the command.

**Comment by davisjam** [comment]
substack hasn't engaged with this proejct for years.

The folks at npm gave me publish rights 1-2 years ago, and I publish updates to the npm registry out of my fork.

Post over there if you have any questions.
