### ISSUE TITLE
(supposedly) safe regex from owasp fails?

### ISSUE THREAD

**Issue by modosc** [substack/safe-regex#7]
this regex comes from [owasp's validation regexp repository](https://www.owasp.org/index.php/OWASP_Validation_Regex_Repository)

```
> var safe = require('safe-regex')
undefined
> safe('^\d{5}(-\d{4})?$')
false
```

i don't understand the math behind this module so i can't say for sure what's going on. is this a false positive or should i ping owasp to update their site?

**Comment by substack** [comment]
This module ensures that the star height is 1, which should all be guaranteed to be safe. There are safe regexes with greater star height, but I don't know how to reliably determine which are safe and which are unsafe.

**Comment by modosc** [comment]
ok thanks!
